package com.bigtech.slot.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class DrinkAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertDrinkAllPropertiesEquals(Drink expected, Drink actual) {
        assertDrinkAutoGeneratedPropertiesEquals(expected, actual);
        assertDrinkAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertDrinkAllUpdatablePropertiesEquals(Drink expected, Drink actual) {
        assertDrinkUpdatableFieldsEquals(expected, actual);
        assertDrinkUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertDrinkAutoGeneratedPropertiesEquals(Drink expected, Drink actual) {
        assertThat(expected)
            .as("Verify Drink auto generated properties")
            .satisfies(e -> assertThat(e.getId()).as("check id").isEqualTo(actual.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertDrinkUpdatableFieldsEquals(Drink expected, Drink actual) {
        assertThat(expected)
            .as("Verify Drink relevant properties")
            .satisfies(e -> assertThat(e.getNome()).as("check nome").isEqualTo(actual.getNome()))
            .satisfies(e -> assertThat(e.getMarca()).as("check marca").isEqualTo(actual.getMarca()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertDrinkUpdatableRelationshipsEquals(Drink expected, Drink actual) {}
}
